"""
Create Event Tool for LangChain agents.

This tool allows LLM agents to create calendar events with proper validation
and database persistence.
"""

import logging
from typing import Optional
from datetime import datetime
from langchain_core.tools import StructuredTool
from pydantic import BaseModel, Field
from adapter.event_adapter import EventAdapter
from database import get_async_db_context_manager
from models import EventCreate

logger = logging.getLogger(__name__)


class CreateEventInput(BaseModel):
    """Input schema for the create_event tool."""
    
    title: str = Field(..., description="The title of the event")
    startDate: datetime = Field(..., description="When the event starts (ISO 8601 format: YYYY-MM-DDTHH:MM:SS±HH:MM)")
    endDate: Optional[datetime] = Field(
        None, 
        description="When the event ends. If not provided, defaults to startDate"
    )
    location: Optional[str] = Field(
        None,
        description="Location of the event. If not provided, defaults to null"
    )


    class Config:
        json_schema_extra = {
            "example": {
                "title": "Meeting with Sarah",
                "startDate": "2025-03-20T14:00:00-05:00",
                "endDate": "2025-03-20T15:00:00-05:00",
                "location": "Conference Room A"
            }
        }


async def create_event_impl(
    title: str,
    startDate: datetime,
    endDate: Optional[datetime] = None,
    location: Optional[str] = None,
    user_id: Optional[int] = None
) -> dict:
    """
    Create a calendar event.
    
    Args:
        title: The title of the event
        startDate: When the event starts
        endDate: When the event ends (defaults to startDate if not provided)
        location: Location of the event (optional, defaults to None)
        user_id: User ID to associate the event with (required, injected from state)
    
    Returns:
        Dictionary with event details including event_id (UUID generated by database)
    
    Raises:
        ValueError: If user_id is not provided
        Exception: If event creation fails
    """
    if user_id is None:
        raise ValueError("user_id is required but was not provided")
    
    # Default endDate to startDate if not provided
    if endDate is None:
        endDate = startDate
    
    logger.info(f"Creating event '{title}' for user {user_id}")
    
    try:
        # Calculate duration from startDate and endDate
        duration_minutes = None
        if endDate != startDate:
            delta = endDate - startDate
            duration_minutes = int(delta.total_seconds() / 60)
        
        # Create EventCreate model
        event_data = EventCreate(
            title=title,
            startDate=startDate,
            duration=duration_minutes,
            location=location
        )
        
        # Use adapter to create event (event_id UUID is generated by database model)
        async with get_async_db_context_manager() as db:
            adapter = EventAdapter(db)
            created_event = await adapter.create_event(user_id, event_data)
            
            logger.info(f"Successfully created event {created_event.id} for user {user_id}")
            
            return {
                "event_id": created_event.id,  # UUID generated by database
                "title": created_event.title,
                "startDate": created_event.startDate.isoformat(),
                "endDate": created_event.endDate.isoformat(),
                "location": created_event.location,
                "user_id": created_event.user_id,
                "success": True
            }
    except Exception as e:
        logger.error(f"Error creating event: {e}", exc_info=True)
        raise Exception(f"Failed to create event: {str(e)}")


def create_event_tool_factory(user_id: int) -> StructuredTool:
    """
    Factory function to create a create_event tool bound to a specific user_id.
    
    Args:
        user_id: The user ID to inject into the tool
    
    Returns:
        A StructuredTool instance configured for the user
    """
    async def create_event_with_user_id(
        title: str,
        startDate: datetime,
        endDate: Optional[datetime] = None,
        location: Optional[str] = None
    ) -> dict:
        """Create event with user_id injected."""
        return await create_event_impl(
            title=title,
            startDate=startDate,
            endDate=endDate,
            location=location,
            user_id=user_id
        )
    
    return StructuredTool.from_function(
        func=create_event_with_user_id,
        name="create_event",
        description="""Create a new calendar event. 
        
        Use this tool when the user wants to schedule or create a new event.
        The event_id will be automatically generated as a UUID.
        If endDate is not provided, it will default to startDate.
        If location is not provided, it will be null.
        """,
        args_schema=CreateEventInput,
    )


# Note: Use create_event_tool_factory(user_id) to create a tool instance bound to a user_id.
# The factory pattern ensures user_id is properly injected and not exposed to the LLM.
